title: Zion R.
author: Zion
email: zrosado@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
 A website including my name, picture, social media info, and 3 facts about myself.

# social links
twitter_username: ZilentNoizes # DO NOT include the @ character, or else the build will fail!
github_username:  ZiRosa # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-tactile
